// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://parnsondoexpphcnqnhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcm5zb25kb2V4cHBoY25xbmhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzI1MzIsImV4cCI6MjA1Nzg0ODUzMn0.6pYxBLpczPgjp3FV2-52ygt8-8P-59VEwF9XAV73JJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);